In [2]:
6-1
tensor1=tf.constant([[1,2],[3,4]],dtype=tf.int64)
tensor2=tf.constant([[5,6],[7,8]],dtype=tf.int64)
def maxnum(tensor1,tensor2):
    res=tf.Variable(tf.zeros(tensor1.shape,dtype=tf.int64 ),dtype=tf.int64)
    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        a=tf.where(tf.greater(tensor1,tensor2),
                        tensor1,
                        tensor2)
        print(sess.run(a))
maxnum(tensor1,tensor2)

[[5 6]
 [7 8]]


In [3]:
6-2
#tf.maximum：用法tf.maximum(a,b),返回的是a,b之间的最大值，
a=tf.constant([[1,2],[3,4]])
b=tf.constant([[5,6],[7,8]])
f1=tf.maximum(a,b)
with tf.Session() as sess:
    print(sess.run(f1))

[[5 6]
 [7 8]]


In [4]:
#tf.miniimum：用法tf.miiinimum(a,b),返回的是a,b之间的最小值
a=tf.constant([[1,2],[3,4]])
b=tf.constant([[5,6],[7,8]])
f2=tf.minimum(a,b)
with tf.Session() as sess:
    print(sess.run(f2))

[[1 2]
 [3 4]]


In [ ]:
6-3
#TensorArray可以看做是具有动态size功能的Tensor数组。
#通常都是跟while_loop或map_fn结合使用
import tensorflow as tf
def cond(time,out):
    return tf.less(time,3)
def body(time,out):
    out=out.write(time,[2.4,3.5])
    return time+1,out
time=tf.constant(0)
out=tf.TensorArray(dtype=tf.float32,size=1,dynamic_size=True)
result=tf.while_loop(cond,body,[time,out])
last_time,last_out=result
final_out=last_out.stack()

with tf.Session() as sess:
    print(last_time.eval())
    print(final_out.eval())
    