In [2]:
2-1
import tensorflow as tf
x=2
y=3
g=tf.Graph()
with g.as_default():
    a=tf.add(x,y)
with tf.Session(graph=g) as sess:
    print(sess.run(a))

sess=tf.Session(graph=g)
print(sess.run(a))
sess.close()

5
5


In [6]:
2-2
#tf.add() 将参数相加 
x=2
y=3
a=tf.add(x,y)
with tf.Session() as sess:
    print(sess.run(a))
    

5


In [8]:
#tf.subtract()    减法操作
x=2
y=3
a=tf.subtract(x,y)
with tf.Session() as sess:
    print(sess.run(a))
    

-1


In [11]:
#tf.multiply()   乘法操作
x=2
y=3
a=tf.multiply(y,x)
with tf.Session() as sess:
    print(sess.run(a))
    

6


In [18]:
#tf.divide()   除法操作

x = tf.constant([[-1.5, 0, 2]], dtype=tf.float32)
y = tf.constant([[2, 0, 1]], dtype=tf.float32)
with tf.Session() as sess:  
    a=tf.divide(x,y)
    print(sess.run(a))

[[-0.75   nan  2.  ]]


In [19]:
#tf.mod()   取模操作
x = tf.constant([[-1.5, 0, 2]], dtype=tf.float32)
y = tf.constant([[2, 0, 1]], dtype=tf.float32)
with tf.Session() as sess:  
    a=tf.mod(x,y)
    print(sess.run(a))

[[0.5 nan 0. ]]


In [22]:
#tf.pow() 幂值计算
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[8, 16], [2, 3]])
with tf.Session() as sess:
    print(sess.run(tf.pow(x, y)))  # [[256, 65536], [9, 27]]


[[  256 65536]
 [    9    27]]


In [23]:
#tf.square() 计算 x 元素的平方。
with tf.Session() as sess:
    print(sess.run(tf.square(x)))

[[4 4]
 [9 9]]


In [26]:
#tf.sqrt() 计算x元素的平方根。
#函数参数：

    #x：一个 Tensor 或 SparseTensor，
    #必须是下列类型之一：half，float32，float64，complex64，complex128。
x = tf.constant([[2, 2], [3, 3]],dtype=tf.float32)
with tf.Session() as sess:
    print(sess.run(tf.sqrt(x)))

[[1.4142135 1.4142135]
 [1.7320508 1.7320508]]
